# Generated by Django 2.0.7 on 2018-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='siteagro/static/siteagro/images/goods')),
                ('kozhura', models.TextField(max_length=250)),
                ('makot', models.TextField(max_length=250)),
                ('forma', models.TextField(max_length=250)),
                ('deep', models.TextField(max_length=250)),
            ],
        ),
    ]
