# Generated by Django 2.0.7 on 2018-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='cancer',
            field=models.TextField(default=4, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='export',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='lezh',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='origin',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='starch',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
