# Generated by Django 2.0.7 on 2018-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0011_auto_20180909_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(help_text='Поле для текста новости', max_length=2000, verbose_name='новость'),
        ),
    ]
