# Generated by Django 2.0.7 on 2018-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0012_auto_20180909_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.FileField(upload_to='siteagro/news', verbose_name='Загрузите новость'),
        ),
    ]
