# Generated by Django 2.0.7 on 2018-09-11 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0013_auto_20180911_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.FileField(upload_to='siteagro/news', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Загрузите новость'),
        ),
    ]
