# Generated by Django 2.0.7 on 2018-09-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0014_auto_20180911_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(help_text='поле для заголовка', max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='полу для новости', verbose_name='новость'),
        ),
    ]
