# Generated by Django 2.0.7 on 2018-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteagro', '0015_auto_20180911_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='vitalik umnichaet op9t. salna9 golova gde navi?', help_text='краткое описание новости', max_length=50, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='полe для новости', verbose_name='новость'),
        ),
    ]
